const APPLICATION_STATUS = {
  SUBMITTED: 'submitted',
  UNDER_REVIEW: 'under_review',
  SCREENING: 'screening',
  INTERVIEWING: 'interviewing',
  ASSESSMENT: 'assessment',
  REFERENCE_CHECK: 'reference_check',
  OFFER_PENDING: 'offer_pending',
  OFFER_ACCEPTED: 'offer_accepted',
  HIRED: 'hired',
  REJECTED: 'rejected',
  WITHDRAWN: 'withdrawn',
  ON_HOLD: 'on_hold'
};

const APPLICATION_STATUS_LABELS = {
  [APPLICATION_STATUS.SUBMITTED]: 'Application Submitted',
  [APPLICATION_STATUS.UNDER_REVIEW]: 'Under Review',
  [APPLICATION_STATUS.SCREENING]: 'Initial Screening',
  [APPLICATION_STATUS.INTERVIEWING]: 'Interviewing',
  [APPLICATION_STATUS.ASSESSMENT]: 'Assessment',
  [APPLICATION_STATUS.REFERENCE_CHECK]: 'Reference Check',
  [APPLICATION_STATUS.OFFER_PENDING]: 'Offer Pending',
  [APPLICATION_STATUS.OFFER_ACCEPTED]: 'Offer Accepted',
  [APPLICATION_STATUS.HIRED]: 'Hired',
  [APPLICATION_STATUS.REJECTED]: 'Not Selected',
  [APPLICATION_STATUS.WITHDRAWN]: 'Withdrawn',
  [APPLICATION_STATUS.ON_HOLD]: 'On Hold'
};

const APPLICATION_STATUS_FLOW = [
  APPLICATION_STATUS.SUBMITTED,
  APPLICATION_STATUS.UNDER_REVIEW,
  APPLICATION_STATUS.SCREENING,
  APPLICATION_STATUS.INTERVIEWING,
  APPLICATION_STATUS.ASSESSMENT,
  APPLICATION_STATUS.REFERENCE_CHECK,
  APPLICATION_STATUS.OFFER_PENDING,
  APPLICATION_STATUS.OFFER_ACCEPTED,
  APPLICATION_STATUS.HIRED
];

module.exports = {
  APPLICATION_STATUS,
  APPLICATION_STATUS_LABELS,
  APPLICATION_STATUS_FLOW
};
